### ISSUE TITLE
what is the value of ipOfServer

### ISSUE THREAD

**Issue by akashsoni143786** [chandilsachin/VideoDownloadAndPlay#2]
what should i pass ipOfServer value in the startServer method

**Comment by chandilsachin** [comment]
Use this: 127.0.0.1 and Have a look at this [VideoPlayerAndDownloaderDemo](https://github.com/chandilsachin/VideoPlayerAndDownloaderDemo) for complete working example.
Or you can just check this url: 
[https://github.com/chandilsachin/VideoPlayerAndDownloaderDemo/blob/master/app/src/main/java/com/sachinchandil/myapplication/VideoStreamDownloaderFragment.java](https://github.com/chandilsachin/VideoPlayerAndDownloaderDemo/blob/master/app/src/main/java/com/sachinchandil/myapplication/VideoStreamDownloaderFragment.java)

**Comment by chandilsachin** [comment]
Did it work? I am closing this issue.
